# Generated by Django 5.1.1 on 2024-12-20 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0004_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField()),
                ('totalprice', models.PositiveIntegerField()),
                ('orderid', models.PositiveIntegerField(default='0')),
                ('proid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom.product')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom.registration')),
            ],
        ),
    ]
