# Generated by Django 5.1.1 on 2025-01-17 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0006_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_price',
            new_name='Grand_price',
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.PositiveBigIntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='order',
            name='qty',
            field=models.PositiveIntegerField(default='0'),
        ),
    ]
