# Generated by Django 5.1.1 on 2025-01-17 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0007_rename_total_price_order_grand_price_order_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
    ]
