# Generated by Django 5.1.1 on 2025-01-17 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0008_remove_order_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='order',
        ),
    ]
