# Generated by Django 5.1.1 on 2025-01-17 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0009_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pin', models.CharField(max_length=6)),
                ('Grand_price', models.PositiveBigIntegerField()),
                ('Total_price', models.PositiveBigIntegerField()),
                ('payment_mode', models.CharField(max_length=20)),
                ('transaction_id', models.CharField(max_length=100)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('mob', models.CharField(default='0', max_length=10)),
                ('qty', models.PositiveIntegerField(default='0')),
                ('order_detail', models.CharField(max_length=4)),
                ('proid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom.product')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom.registration')),
            ],
        ),
    ]
