# Generated by Django 5.1.1 on 2025-03-22 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0010_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_detail',
        ),
        migrations.AddField(
            model_name='order',
            name='orderid',
            field=models.TextField(blank=True, default='cod'),
        ),
    ]
