# Generated by Django 5.1.1 on 2025-03-22 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0011_remove_order_order_detail_order_orderid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Grand_price',
        ),
    ]
